### ISSUE TITLE
Check you configuration + passphrase issue

### ISSUE THREAD

**Issue by incoming-th** [stechstudio/laravel-ssh-tunnel#14]
Hi,

This script seems to be what I was looking for but I don't know if I am using it wrong or if issue with server.

I tried to use it on Laravel 5.4 and I got this message:

![2017-11-19 002321](https://user-images.githubusercontent.com/26375917/32988142-54f614be-cd30-11e7-80f3-ee4723677f77.png)

1. The command throw an error, I have checked all settings and they seem fine.
2. Just after that the command launch a new one asking for passphrase, but I don't have passphrase on the RSA key.
3. I have whitelisted the server IP so no issue from here

Just wondering what i am doing wrong :)

**Comment by bubba-h57** [comment]
Does running that SSH Tunnel command manually work properly for you?

**Comment by incoming-th** [comment]
It seems my host does not authorize SSH Tunneling so end of story I think.
