### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by corneliusve** [stechstudio/laravel-ssh-tunnel#15]
when i do a php artisan commant it says: 

In CreateTunnel.php line 54: parse error, expecting `';'' or `'{''

How can i fix this?

**Comment by jszobody** [comment]
You're probably running PHP 5.x? This package requires PHP 7.

**Comment by corneliusve** [comment]
How can i update that?

**Comment by jszobody** [comment]
Upgrading PHP depends on your webhost, or your local development environment. You'll need to go use google/stackoverflow to figure out how to get PHP version 7.x setup for your particular environment.

Note PHP 7 is also required for Laravel 5.5, you'll want to get that sorted for sure.
