### ISSUE TITLE
Could Not Create SSH Tunnel with command

### ISSUE THREAD

**Issue by DennisHUtrecht** [stechstudio/laravel-ssh-tunnel#17]
This is what I get every time.

I am running my Laravel application in laradock, with nginx mysql.
I am trying to connect to a remote server on xxx.com. 
All the required data is available. But I keep getting this error message.
So I tried to debug it, and when I put in the command when in the workspace (logged in on the linux machine) I can access SSH. It just does not give me an exit code, is that what you guys expect with return (bool)($return_var === 0);?
Can we force to give it an exit code? 

This might be a super noob question, but I'm pretty new to docker AND opening ssh connections, so please excuse me for that.

**Comment by DennisHUtrecht** [comment]
Whenever I dump these two:

```
        exec($command, $this->output, $return_var);
        dump($this->output);
        dump($return_var);
```
 I get this:
> []
> 1
> []
> 0
> []
> 1

**Comment by V13Axel** [comment]
> But I keep getting this error message

What error message?

**Comment by DennisHUtrecht** [comment]
The error message that the package gives: Could Not Create SSH Tunnel with command /ssh command here/

**Comment by tokoiwesley** [comment]
I get the same error when trying to connect to a remote server.

**Comment by bubba-h57** [comment]
Pull the latest version and open a new ticket if you continue to have issues.
