### ISSUE TITLE
multiple connections

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [stechstudio/laravel-ssh-tunnel#20]
Hey.

I need to keep multiple connections up and running - can you recommend a better way to do it?

**Comment by bubba-h57** [comment]
It would not be hard. Take a look at the [CreateTunnel->handle()](https://github.com/stechstudio/laravel-ssh-tunnel/blob/master/src/Jobs/CreateTunnel.php#L54) method. On [line 82](https://github.com/stechstudio/laravel-ssh-tunnel/blob/master/src/Jobs/CreateTunnel.php#L82) you can see where we created the command from the config. You just need to generate a unique command for each connection you want and run it.

You could do it manually, or modify the configuration to handle multiple connections.
