### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by jamiehd** [stechstudio/laravel-ssh-tunnel#21]
Hi,

Does this support Lumen? If not is there any plans to make it work with Lumen?

Thanks,

Jamie

**Comment by bubba-h57** [comment]
Do you even [README](https://github.com/stechstudio/laravel-ssh-tunnel#installation) bro?

The short answer is, yes, this runs in Lumen or Laravel. The long answer is, read the docs before opening an issue. We wrote them to prevent being asked trivial questions like this.

**Comment by jamiehd** [comment]
Sorry about that! I've apparently lost the ability to read. I'll do my best to regain it before opening any more issues...

**Comment by bubba-h57** [comment]
You made me smile on Tuesday morning. That was worth it.
