### ISSUE TITLE
Unexpected Eventuality

### ISSUE THREAD

**Issue by SturmB** [stechstudio/laravel-ssh-tunnel#22]
Well, I decided to try out this package for the first time with a Laravel 5.6 project and I got the one error message that I hoped never to see:
```
> /usr/local/bin/php /Users/apache/Sites/acs/artisan tunneler:activate
I have no idea how this happened. Let me know if you figure it out.

Process finished with exit code 1 at 16:04:54.
Execution time: 433 ms.
```

So, since I'm still very much an amateur with Laravel and web development in general, this one is completely out of my hands and I'll have to pursue other means of connecting to a MySQL database over SSH. Thanks for trying, though.

**Comment by bubba-h57** [comment]
I don't know how I missed this, but this is clearly most awesome bug report ever!
