### ISSUE TITLE
strange error when activate tunnel

### ISSUE THREAD

**Issue by physio** [stechstudio/laravel-ssh-tunnel#24]
this is my output:
root@a89cada6a576:/var/www# php artisan tunneler:activate
I have no idea how this happened. Let me know if you figure it out.

   ErrorException  : Could Not Create SSH Tunnel with command:
        ssh   -N -i  -L 0:127.0.0.1:0 -p 0 @
Check your configuration.

and this is my configuration:

TUNNELER_IDENTITY_FILE=/var/www/xxxxxx.pem
TUNNELER_LOCAL_PORT=15432
TUNNELER_LOCAL_ADDRESS=127.0.0.1
TUNNELER_BIND_PORT=5432
TUNNELER_BIND_ADDRESS=xxxxxxxxxx.eu-west-1.rds.amazonaws.com
TUNNELER_USER=ubuntu
TUNNELER_HOSTNAME=52.xxx.xxx.xxx
TUNNELER_PORT=22
TUNNELER_CONN_WAIT=500000
TUNNELER_CONN_TRIES=1
TUNNELER_ON_BOOT=false
TUNNELER_SSH_OPTIONS="-o StrictHostKeyChecking=no"

the server is amazon rds postgre db.

**Comment by bubba-h57** [comment]
It is attempting to create the tunnel with only [default settings](https://github.com/stechstudio/laravel-ssh-tunnel/blob/master/config/tunneler.php).  For some reason, the configuration you have in your `.env` file is not getting picked up. 

I suggest verifying that your `.env` is working properly and troubleshoot from there.
