### ISSUE TITLE
SSH connection uses password instead of rsa file

### ISSUE THREAD

**Issue by vvp242424** [stechstudio/laravel-ssh-tunnel#25]
Hello, 

I have a kinsta server setup that requires a SSH connection to the database but they handle it as a password, not a private key file. here is a screenshot of what the sequel pro connection looks like https://gyazo.com/429c11be1d6e64737e22f64cc29109c0

Any help with how I can tweak the env file to connect via that password, much appreciated.

**Comment by bubba-h57** [comment]
There is currently no way to configure this to use a password. If someone implements it and gives us a pull request, that would be great.

**Comment by jszobody** [comment]
Side note: Kinsta allows you to use key based SSH logins:

https://kinsta.com/knowledgebase/connect-to-ssh/

**Comment by vvp242424** [comment]
Thank you both for the quick response. I'll go the key based way that @jszobody mentioned.
