### ISSUE TITLE
Support to laravel 5.8

### ISSUE THREAD

**Issue by jlhumerez** [stechstudio/laravel-ssh-tunnel#27]
In laravel I get the following error, when executing php artisan tunneler: active

### Fatal error: Uncaught ReflectionException: Class config does not exist in /Users/humerez/Sites/manage/vendor/laravel/framework/src/Illuminate/Container/Container.php:790
Stack trace:
#0 /Users/humerez/Sites/manage/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): ReflectionClass->__construct('config')
#1 /Users/humerez/Sites/manage/vendor/laravel/framework/src/Illuminate/Container/Container.php(667): Illuminate\Container\Container->build('config')
#2 /Users/humerez/Sites/manage/vendor/laravel/framework/src/Illuminate/Container/Container.php(615): Illuminate\Container\Container->resolve('config', Array)
#3 /Users/humerez/Sites/manage/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(767): Illuminate\Container\Container->make('config', Array)
#4 /Users/humerez/Sites/manage/vendor/laravel/framework/src/Illuminate/Container/Container.php(1225): Illuminate\Foundation\Application->make('config')
#5 /Users/humerez/Sites/manage/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.ph in /Users/humerez/Sites/manage/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 790

**Comment by bubba-h57** [comment]
Huh, this was never closed.
