### ISSUE TITLE
If I use in the development of Windows what parameters I should set here is a little incomprehensible.

### ISSUE THREAD

**Issue by asyou99** [stechstudio/laravel-ssh-tunnel#35]
; Process used to verify connection
; Use bash if your distro uses nmap-ncat (RHEL/CentOS 7.x) 
TUNNELER_VERIFY_PROCESS=nc

; Path to the nc executable
TUNNELER_NC_PATH=/usr/bin/nc
; Path to the bash executable
TUNNELER_BASH_PATH=/usr/bin/bash
; Path to the ssh executable
TUNNELER_SSH_PATH=/usr/bin/ssh
; Path to the nohup executable
TUNNELER_NOHUP_PATH=/usr/bin/nohup

**Comment by bubba-h57** [comment]
You need to ensure those tools are installed and you will need to know the path to them.

The tools are not installed on Windows machines by default, and I don't support windows. However, if you get it sorted out, please leave a PR to update the documentation for windows~

**Comment by perle-rare** [comment]
Hi @ASYOU99 , Please did you get this to work under Windows ??
Thanks
