### ISSUE TITLE
The command worksin Terminal, not via Laravel

### ISSUE THREAD

**Issue by ligne13** [stechstudio/laravel-ssh-tunnel#37]
Hi,

The command fails when running via Laravel, however the command runs well when I run it manually in the Terminal.

The error:
```
Could Not Create SSH Tunnel with command: /usr/bin/ssh -N -i /home/vagrant/.ssh/id_rsa -L 61215:my_database_host:3306 -p 22 user@server
```

I'm using Homestead.

Any idea why ?

**Comment by CrixuAMG** [comment]
Also unable to establish a working SSH connection via the terminal, but not via Laravel...
I've tried using different options for the command, different ports, but have not been able to get it working.

Running 2.0.1 of this package, calling CreateTunnel using dispatch_now, Laravel composer constraint ^5.8.0
