### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by vesper8** [stechstudio/laravel-ssh-tunnel#39]
`2.0` is not compatible with Laravel 7 due to `illuminate/support ^5.5|^6.0`

It's probably just a matter of appending `|^7.0` to the `composer.json`

@bubba-h57 Could you please release a new version with Laravel 7 compatibility?

Thanks a lot!

**Comment by bubba-h57** [comment]
Done!

**Comment by vesper8** [comment]
thank you : )
