### ISSUE TITLE
Tunnel created but still returned error

### ISSUE THREAD

**Issue by anujkaushal** [stechstudio/laravel-ssh-tunnel#40]
When you run the activate command it creates the tunnel but still return error.
Also when you run the command again it verifies that tunnel already exists.
![image](https://user-images.githubusercontent.com/32764738/80712453-a491a480-8b0f-11ea-82dd-caf76ac8655d.png)

**Comment by anujkaushal** [comment]
My configurations:
`TUNNELER_VERIFY_PROCESS=ssh`
`TUNNELER_CONN_WAIT=1000000`
`TUNNELER_SSH_OPTIONS="-o StrictHostKeyChecking=no"`

**Comment by bubba-h57** [comment]
I have not been able to reproduce the problem, and thus can't rightly troubleshoot it. Have you made any progress in sorting it out yourself?

**Comment by cearls** [comment]
I am getting the same error even though the tunnel is created. I use Homestead for local dev and thought it might be that, but it is doing it in production as well.

I'll see what I can find out.

**Comment by cearls** [comment]
I got this worked out. I realized you can't use ssh as a verify process. So, I double-checked my nc path, and it was wrong. It should have been `/bin/nc` vs. `/usr/bin/nc`.

@bubba-h57 Thanks for the great package!

**Comment by bubba-h57** [comment]
That is outstanding and thanks for the encouragement as well!
