### ISSUE TITLE
Crash when running php artisan tunneler:activate

### ISSUE THREAD

**Issue by lYesterdaYl** [stechstudio/laravel-ssh-tunnel#41]
Hi, I am trying to connect to a remote server and access its mysql database. When I run the command "php artisan tunneler:activate". It seems fine for like 3 second, and then an error pops up and stop the command. Does anyone know why?
![image](https://user-images.githubusercontent.com/5135163/91920972-373d7e00-ec7f-11ea-83db-f5e131ef79fd.png)

The command inside the error. When I copy it out alone and run it. No problems at all...

**Comment by scorgn** [comment]
You likely have the `ssh2` module loaded twice in your `php.ini`. It's possible you have multiple ini files loaded both with the plugin. As you can see, before getting the actual exception, it shows `PHP Warning: Module 'ssh2'  already loaded in Unknown on line 0`
