### ISSUE TITLE
How to Close/Deactivate already running tunnel ?

### ISSUE THREAD

**Issue by MuhammadSulman** [stechstudio/laravel-ssh-tunnel#43]

**Comment by bubba-h57** [comment]
I'll need more context to answer that. In general, the library is only expected to manage tunnels it opens itself though.

**Comment by bubba-h57** [comment]
Closed due to lack of response.

**Comment by vesper8** [comment]
To kill all active ssh tunnels you can run this `sudo killall ssh`
