### ISSUE TITLE
Could not establish tunnel

### ISSUE THREAD

**Issue by cnngraphics** [stechstudio/laravel-ssh-tunnel#44]
Anyone is suffering similar issue?

I have to connect to an RDS Database on AWS through a bastion host
I am getting error

```
Could Not Create SSH Tunnel with command:
        /usr/bin/ssh -o StrictHostKeyChecking=no  -N -i /home/pcims/.ssh/id_rsa -L 13308:127.0.0.1:3306 -p 2220 ssh_username@jumpbox Check your configuration.
        ```

**Comment by AdvancedStyle** [comment]
I'm having the same problem on Ubuntu 20.04.

Even though the tunnel has been created, and is working.

```
php artisan tunneler:activate
Could Not Create SSH Tunnel with command:
        /usr/bin/ssh -o StrictHostKeyChecking=no  -N -i /home/me/.ssh/id_rsa -L 13306:127.0.0.1:3306 -p 22 myuser@xxx.xxx.xxx.xxx
Check your configuration.
```

**Comment by AdvancedStyle** [comment]
My issue was just mis-configuration.

Did not have the correct **TUNNELER_NC_PATH**. 

Check `/usr/bin/nc` exists and if not `which nc` to locate it (in my case it was at `/bin/nc`).
