### ISSUE TITLE
Unable to disable -i option, which breaks authenticating via ssh-agent

### ISSUE THREAD

**Issue by paulcdejean** [stechstudio/laravel-ssh-tunnel#45]
Hello in a local dev environment we are using ssh-agent: https://www.ssh.com/ssh/agent

However this library forces ssh to use the -i option, which disables authenticating via ssh agent.

When the `TUNNELER_IDENTITY_FILE` option is unset, the -i option should be excluded.

**Comment by bubba-h57** [comment]
Check out https://github.com/stechstudio/laravel-ssh-tunnel/pull/49 and let me know if that solves the issue for you.
