### ISSUE TITLE
Pass pwd through laravel ssh package

### ISSUE THREAD

**Issue by marcpre** [stechstudio/laravel-ssh-tunnel#46]
Hello,

I still have `PasswordAuthentication = yes` on my ssh.

Is there a way to pass the password via the ssh tunnel?

I appreciate your reply!

**Comment by jszobody** [comment]
There is currently no way to configure this to use a password. We just don't have any need for that ourselves.

If you wanted to implement it and provide a pull-request we'd be happy to consider it.
