### ISSUE TITLE
Tunnel activates and stays active, mysql won't connect

### ISSUE THREAD

**Issue by stangsdado** [stechstudio/laravel-ssh-tunnel#53]
I've been using this with 100% success for about a year on a Laravel 5.7/Ubuntu 18.04 setup. Now, I'm building a new app using Laravel 8 on Ubuntu 20.04 and I've got a problem.

Tunnel will activate but any mysql connection via Laravel app will produce:
`SQLSTATE[HY000] [2006] MySQL server has gone away (SQL: select * from `****`)`

I attempted to manually connect to the mysql server using command line via active tunnel and it hangs for 30 seconds until:
`ERROR 2003 (HY000): Can't connect to MySQL`

If I use an IDE (Sequel Ace in this case) with the identical settings (ports, hosts, identity file, etc), I'm able to connect to the mysql server without a problem.

**Comment by NH-FS** [comment]
Oooo this is almost 1 year old. I am trying this for the first time, getting the same error.
