### ISSUE TITLE
Add a php artisan command to destroy the tunnel

### ISSUE THREAD

**Issue by JoyKevinMaldini** [stechstudio/laravel-ssh-tunnel#58]
I've just started using this package and think it's awesome. What I've noticed though is that there either might be an error in the setup or it just needs an option to also close the tunnel again.

Currently there isn't any option to close / destroy the tunnel, right? I would like to have that option.

`php artisan tunneler:deactivate` or `php artisan tunneler:destroy` would make sense..?

The reason I'm coming up with this is that I need it for multiple projects simultaneously. Now when I open one tunnel it works for that project, when I then try to open another tunnel in another project directory, the artisan command tells me that "The Tunnel is already Activated." which makes me unable to connect to that project as well.

Or did I just miss some configuration in the .env where we would be able to give the tunnel a name or tag or something? If I just missed some things then maybe an update for the README would be appreciated. :)

Ps: This is my first ever comment on such a package / project so I hope I'm at the right place here and didn't make any errors.

**Comment by JoyKevinMaldini** [comment]
I just noticed I got redirected to the old / out of date repo.. Can't find the "Issues" tab on the forked repo though. Not sure how to proceed.

**Comment by haztakki** [comment]
Hello @JoyKevinMaldini,

This repo is marked as **_Abandoned_**.

https://github.com/stechstudio/laravel-ssh-tunnel#readme

Are you using the new repo?

I would pull in the following package if you haven't done so already.

https://packagist.org/packages/prodigyphp/laravel-ssh-tunnel

As for your issue, I haven't used this package myself. The new repo does not have "Issues" enabled so I'm not sure how you can get further support. Maybe someone else can be of more help.

Edit: Just noticed your second comment.

**Comment by iambateman** [comment]
Issues are added on the forked package, here: https://github.com/prodigyphp/laravel-ssh-tunnel/issues

Apologies, all! I didn't realize it wasn't on.

**Comment by JoyKevinMaldini** [comment]
@iambateman Thanks so much for replying so fast and getting the issues up. :)
